name: Despliegue a EC2 via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Obtiene el código del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Despliega archivos a EC2 usando SSH
      - name: Deploy 'src' folder to EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          # Parámetros de conexión usando tus secretos de EC2
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "src/"
          target: "/usr/share/nginx/html"
          