name: Despliegue a EC2 via SSH/SCP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy 'src' folder to Nginx Root
        uses: appleboy/scp-action@v0.1.7 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }} 
          
          source: "src/" 
          target: "/usr/share/nginx/html"
          
      - name: Reload Nginx Service
        uses: appleboy/ssh-action@v1.0.1 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Archivos transferidos. Recargando Nginx..."
            sudo systemctl reload nginx