name: Despliegue a S3

on:
  workflow_dispatch:

jobs:
  despliegue-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install

      - name: Subir al bucket
        run: |
          echo "Subiendo archivos a S3..."
          aws s3 sync ./src s3://${{ secrets.AWS_S3_BUCKET }}/
     