name: Despliegue a S3

on:
  workflow_dispatch:

jobs:
  despliegue-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install

      - name: Subir al bucket
        run: |
          echo "Subiendo archivos a S3..."
          aws s3 sync ./src s3://${{ secrets.S3_BUCKET_NAME }}/
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
     